In [10]:
import math
import tkinter as tk

In [15]:
tk.help

AttributeError: module 'tkinter' has no attribute 'help'

In [16]:
import numpy as np

In [54]:
MX=np.array(range(1,5))
MX2=np.array(range(1,10))
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])

In [55]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [56]:
np.multiply(a,MX)

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48],
       [13, 28, 45, 64],
       [17, 36, 57, 80]])